export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const GET_PHRASES = 'GET_PHRASES';
export const SET_PHRASES = 'SET_PHRASES';
export const SOLUTION_BUTTON_TEXT = 'SOLUTION_BUTTON_TEXT';
